backend:
  name: git-gateway
  repo: Carms-dev/gegi-law-gatsby-netlify
  branch: master
  commit_messages:
    create: '[ADD][CMS] {{collection}} “{{slug}}”'
    update: '[UPD][CMS] {{collection}} “{{slug}}”'
    delete: '[REM][CMS] {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true

media_folder: static/assets
public_folder: /assets

collections:
  - label: Resources
    name: resources
    folder: content/resources
    create: true
    identifier_field: resourceName
    editor:
      preview: false
    fields:
      - {label: Resource Name, name: resourceName, widget: string, required: true}
      - {label: Highlights, name: highlights, widget: string, required: false}
      - {label: Eligibility, name: eligibility, widget: string, required: true}
      - {label: Service Description, name: serviceDescription, widget: text}
      - {label: Website, name: website, widget: string, required: true}
      - {label: Email, name: email, widget: string, required: false}
      - {label: Phone, name: phone, widget: string, required: false}
      - {label: Logo, name: logo, widget: image, required: true}
      - label: Organization or Firm
        name: resourceType
        widget: select
        options: [Community Organization, Law Firm]
        default: Community Organization
      - label: Service
        name: service
        widget: relation
        collection: serviceCategories
        required: true
        search_fields: [category]
        value_field: category
        display_fields: [category]
      - label: Location
        name: location
        widget: relation
        multiple: true
        required: true
        min: 1
        collection: locationCategories
        search_fields: [category]
        value_field: category
        display_fields: [category]
      - label: Cost
        name: cost
        widget: relation
        required: true
        collection: costCategories
        search_fields: [category]
        value_field: category
        display_fields: [category]

  - label: Cases
    name: cases
    editor:
      preview: false
    folder: content/cases
    create: true
    identifier_field: caseName
    fields:
      - {label: "Is Cornerstone?", name: isCornerstone, widget: boolean, default: false}
      - {label: Case Name, name: caseName, widget: string, required: true}
      - {label: Citation, name: citation, widget: string, required: true}
      - {label: Description, name: description, widget: text, required: true}
      - {label: Takeaway, name: takeaway, widget: text, required: false}
      - {label: Link, name: url, widget: string, required: true}
      - label: Themes
        name: themes
        widget: relation
        multiple: true
        min: 1
        collection: caseThemes
        search_fields: [category]
        value_field: category
        display_fields: [category]

  - label: Pages
    name: pages
    editor:
      preview: false
    files:
      - file: content/pages/home.md
        label: Home Page
        name: homePage
        fields:
          - {label: Title, name: title, widget: string}
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Call to action, name: linkText, widget: string}
          - label: Secondary Call To Action
            name: secondaryCTAs
            widget: object
            fields:
            - {label: Resource Page (CTA), name: resourceCTA, widget: string}
            - {label: Resource Page Icon, name: resourceIcon, widget: object, fields: [{label: Image File, name: imageFile, widget: image}, {label: Alt, name: alt, widget: string}]}
            - {label: Case Page (CTA), name: caseCTA, widget: string}
            - {label: Case Page Icon, name: caseIcon, widget: object, fields: [{label: Image File, name: imageFile, widget: image}, {label: Alt, name: alt, widget: string}]}
          - {label: Introduce Supporter, name: supporterLabel, widget: string}
          - label: Cornerstone Cases Section
            name: caseSection
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: string}
              - {label: Call to action, name: linkText, widget: string}
          - label: About Section
            name: aboutSection
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Description
                name: description
                widget: markdown
                buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
              - {label: Image, name: image, widget: object, fields: [{label: Image File, name: imageFile, widget: image}, {label: Alt, name: alt, widget: string}]}
          - label: Statistics Section
            name: statisticsSection
            widget: object
            fields:
              - {label: Case Label, name: caseLabel, widget: string}
              - {label: Resource Label, name: resourceLabel, widget: string}
              - {label: Province Label, name: provinceLabel, widget: string}
              - {label: "# Provinces", name: provinceCount, widget: number, value_type: int}

      - file: content/pages/start.md
        label: "Get Started Page"
        name: startPage
        fields:
          - {label: Title, name: title, widget: string}
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Image, name: image, widget: object, fields: [{label: Image File, name: imageFile, widget: image}, {label: Alt, name: alt, widget: string}]}
          - label: Disclaimer
            name: disclaimer
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Description
                name: description
                widget: markdown
                buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
          - label: Questions
            name: questions
            widget: list
            summary: '{{fields.question}} - {{fields.selectLabel}}'
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Description, name: description, widget: text, required: false}
              - {label: Select Label, name: selectLabel, widget: string}
              - label: Options
                name: options
                widget: list
                fields:
                - {label: Option, name: option, widget: string}
                - label: Response
                  name: response
                  widget: markdown
                  buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
          - {label: Response Icon, name: responseIcon, widget: image}

      - file: content/pages/resources.md
        label: Resources Page
        name: resourcesPage
        fields:
          - {label: Title, name: title, widget: string}
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Image, name: image, widget: object, fields: [{label: Image File, name: imageFile, widget: image}, {label: Alt, name: alt, widget: string}]}
          - label: Filters
            name: filters
            widget: hidden
            default: ["service", "location", "cost"]

      - file: content/pages/cases.md
        label: Cases Page
        name: casesPage
        fields:
          - {label: Title, name: title, widget: string}
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Image, name: image, widget: object, fields: [{label: Image File, name: imageFile, widget: image}, {label: Alt, name: alt, widget: string}]}
          - {label: Cornerstone Case Icon, name: cornerstoneIcon, widget: image}
          - {label: Non-Cornerstone Case Icon, name: caseIcon, widget: image}

  - label: Settings
    name: settings
    editor:
      preview: false
    files:
      - file: content/settings/site.md
        label: "Site settings"
        name: siteSettings
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Description, name: siteDescription, widget: text}
          - {label: Site Logo, name: siteLogo, widget: image}
          - {label: Site Image, name: siteImage, widget: object, fields: [{label: Image File, name: imageFile, widget: image}, {label: Alt, name: alt, widget: string}]}
          - label: Privacy Policy Page
            name: privacyPage
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Policy
                name: description
                widget: markdown
                buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
          - label: 404 Page
            name: fourOhFourPage
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Description
                name: description
                widget: markdown
                buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
          - label: Footer note
            name: footerNote
            widget: markdown
            buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
          - label: Social Media
            name: socialMedia
            widget: object
            fields:
              - {label: facebook, name: facebook, widget: string, required: false}
              - {label: twitter, name: twitter, widget: string, required: false}
              - {label: instagram, name: instagram, widget: string, required: false}
              - {label: github, name: github, widget: string, required: false}

  - label: Service (Resource Category)
    name: serviceCategories
    editor:
      preview: false
    folder: content/service
    create: true
    identifier_field: category
    fields:
      - {label: Service Category, name: category, widget: string, required: true}

  - label: Cost (Resource Category)
    name: costCategories
    editor:
      preview: false
    folder: content/cost
    create: true
    identifier_field: category
    fields:
      - {label: Fee Category, name: category, widget: string, required: true}

  - label: Location (Resource Category)
    name: locationCategories
    editor:
      preview: false
    folder: content/location
    create: true
    identifier_field: category
    fields:
      - {label: Location Category, name: category, widget: string, required: true}

  - label: Theme (Case Category)
    name: caseThemes
    folder: content/theme
    create: true
    identifier_field: category
    fields:
      - {label: Theme Category, name: category, widget: string, required: true}

  - label: Supporter Logo
    name: supporters
    folder: content/supporters
    create: true
    identifier_field: category
    fields:
      - {label: Title, name: title, widget: string}
      - {label: logo, name: logo, widget: image}
      - {label: Link, name: url, widget: string}
